CREATE OR REPLACE TABLE workspace.virtue_foundation_enriched.dim_specialty_canonical AS
SELECT * FROM (
  VALUES
  ('internal_medicine', 'internal_medicine', 'General internal/adult medicine; the dominant catch-all for adult ambulatory and inpatient physician care.', 68600),
  ('family_medicine', 'primary_care', 'Family/general practice across all ages and primary care.', 23732),
  ('pediatrics', 'maternal_child', 'General pediatrics and child health (excludes pediatric subspecialties mapped separately).', 6800),
  ('adolescent_medicine', 'maternal_child', 'Adolescent and young-adult medicine.', 152),
  ('neonatology', 'maternal_child', 'Neonatal and perinatal newborn intensive care.', 1910),
  ('obstetrics_gynecology', 'maternal_child', 'Combined OB/GYN, maternity and women''s reproductive health.', 12600),
  ('maternal_fetal_medicine', 'maternal_child', 'High-risk pregnancy / maternal-fetal medicine and perinatology.', 1066),
  ('reproductive_endocrinology_infertility', 'maternal_child', 'Fertility, IVF, reproductive endocrinology and assisted reproduction.', 4370),
  ('family_planning_contraception', 'maternal_child', 'Family planning and complex contraception.', 234),
  ('urogynecology', 'maternal_child', 'Urogynecology and female pelvic reconstructive surgery.', 130),
  ('maternal_child_health', 'maternal_child', 'Population-level maternal and child health programs.', 173),
  ('cardiology', 'internal_medicine', 'Adult cardiology including interventional, electrophysiology and preventive cardiology.', 6250),
  ('pediatric_cardiology', 'maternal_child', 'Pediatric cardiology.', 285),
  ('gastroenterology', 'internal_medicine', 'Medical gastroenterology and hepatology (non-surgical).', 4080),
  ('nephrology', 'internal_medicine', 'Nephrology and dialysis.', 3700),
  ('pulmonology', 'internal_medicine', 'Pulmonary / respiratory / chest medicine.', 2470),
  ('endocrinology_diabetes', 'ncd', 'Endocrinology, diabetes and metabolism.', 3150),
  ('rheumatology', 'internal_medicine', 'Rheumatology and clinical immunology of joints/connective tissue.', 720),
  ('infectious_diseases', 'internal_medicine', 'Infectious diseases and infection control.', 1320),
  ('allergy_immunology', 'internal_medicine', 'Allergy and clinical immunology.', 445),
  ('hematology', 'cancer', 'Hematology and hemato-oncology (non-laboratory).', 700),
  ('geriatric_medicine', 'internal_medicine', 'Geriatrics / care of older adults.', 363),
  ('sleep_medicine', 'internal_medicine', 'Sleep medicine across parent disciplines.', 385),
  ('sports_medicine', 'internal_medicine', 'Non-surgical sports and exercise medicine.', 315),
  ('addiction_medicine', 'mental_health', 'Addiction and substance-use disorder medicine (non-psychiatric).', 85),
  ('andrology_sexual_medicine', 'internal_medicine', 'Andrology, male fertility and sexual medicine.', 480),
  ('palliative_medicine', 'internal_medicine', 'Hospice, palliative and supportive care.', 300),
  ('critical_care_medicine', 'internal_medicine', 'Adult intensive / critical care medicine.', 2740),
  ('pediatric_critical_care', 'maternal_child', 'Pediatric intensive / critical care.', 281),
  ('emergency_medicine', 'internal_medicine', 'Emergency and acute / trauma medicine.', 3100),
  ('pediatric_emergency_medicine', 'maternal_child', 'Pediatric emergency medicine.', 51),
  ('anesthesiology', 'surgery', 'Anesthesiology and perioperative / pain anesthesia.', 2000),
  ('pain_medicine', 'physical_rehab', 'Pain medicine and pain management.', 480),
  ('physical_medicine_rehab', 'physical_rehab', 'Physical medicine and rehabilitation (physiatry).', 2520),
  ('physiotherapy', 'physical_rehab', 'Physiotherapy / physical therapy.', 150),
  ('occupational_therapy', 'physical_rehab', 'Occupational therapy and vocational rehabilitation.', 45),
  ('speech_audiology', 'physical_rehab', 'Speech therapy and audiology.', 50),
  ('prosthetics_orthotics_rehab', 'physical_rehab', 'Amputee, prosthetics/orthotics and related rehabilitation.', 85),
  ('dermatology', 'dermatology', 'Medical, cosmetic and procedural dermatology.', 4900),
  ('pediatric_dermatology', 'maternal_child', 'Pediatric dermatology.', 104),
  ('psychiatry', 'mental_health', 'General and subspecialty psychiatry.', 2050),
  ('child_adolescent_psychiatry', 'mental_health', 'Child and adolescent psychiatry.', 115),
  ('psychology', 'mental_health', 'Clinical / counseling psychology.', 70),
  ('neurology', 'neuroscience', 'Adult neurology and clinical neurophysiology subspecialties.', 4000),
  ('pediatric_neurology', 'maternal_child', 'Pediatric / child neurology and neurodevelopment.', 280),
  ('neurosurgery', 'surgery', 'Neurosurgery including spine, skull base, cerebrovascular and functional.', 4100),
  ('pediatric_neurosurgery', 'maternal_child', 'Pediatric neurosurgery.', 88),
  ('general_surgery', 'surgery', 'General surgery including laparoscopic, robotic and hernia surgery.', 5800),
  ('orthopedic_surgery', 'surgery', 'Orthopedic surgery including arthroscopy, joint, spine, trauma, hand, foot, shoulder subspecialties.', 8200),
  ('pediatric_orthopedic_surgery', 'maternal_child', 'Pediatric orthopedic surgery.', 270),
  ('hand_surgery', 'surgery', 'Hand, upper extremity and peripheral nerve surgery.', 120),
  ('spine_surgery', 'surgery', 'Orthopedic spine surgery (non-neuro).', 150),
  ('cardiothoracic_surgery', 'surgery', 'Cardiac, thoracic and cardiovascular surgery.', 1150),
  ('vascular_surgery', 'surgery', 'Vascular and endovascular surgery.', 640),
  ('plastic_reconstructive_surgery', 'surgery', 'Plastic, reconstructive and aesthetic surgery.', 2950),
  ('colorectal_surgery', 'surgery', 'Colorectal surgery and proctology.', 675),
  ('gi_hpb_surgery', 'surgery', 'GI, hepatopancreatobiliary and upper-GI surgical gastroenterology.', 450),
  ('bariatric_metabolic_surgery', 'surgery', 'Bariatric / metabolic / obesity surgery.', 485),
  ('transplant_surgery', 'surgery', 'Organ transplant surgery (liver, kidney, multi-organ).', 615),
  ('pediatric_surgery', 'maternal_child', 'General pediatric surgery.', 875),
  ('urology', 'surgery', 'Urology including endourology, oncology, reconstructive and female urology.', 4900),
  ('pediatric_urology', 'maternal_child', 'Pediatric urology.', 157),
  ('otolaryngology', 'surgery', 'ENT / otolaryngology including rhinology, laryngology, otology and head & neck.', 5300),
  ('pediatric_otolaryngology', 'maternal_child', 'Pediatric otolaryngology.', 144),
  ('ophthalmology', 'eye', 'General ophthalmology and eye care (parent for eye subspecialties not separately keyed).', 8200),
  ('cataract_anterior_segment', 'eye', 'Cataract and anterior-segment surgery.', 1554),
  ('retina_vitreoretinal', 'eye', 'Retina, vitreoretinal disease and diabetic retinopathy.', 1390),
  ('refractive_surgery', 'eye', 'Refractive / LASIK / corneal refractive eye surgery.', 1110),
  ('glaucoma', 'eye', 'Glaucoma ophthalmology.', 997),
  ('cornea', 'eye', 'Cornea and external eye disease.', 984),
  ('oculoplasty_orbit', 'eye', 'Oculoplastics, orbit and ocular reconstructive surgery.', 840),
  ('pediatric_strabismus_ophthalmology', 'eye', 'Pediatric ophthalmology and strabismus/squint.', 830),
  ('neuro_ophthalmology', 'eye', 'Neuro-ophthalmology.', 269),
  ('uveitis', 'eye', 'Uveitis and ocular inflammation.', 230),
  ('ocular_oncology', 'eye', 'Ocular oncology.', 69),
  ('eye_trauma_emergency', 'eye', 'Eye trauma and emergency eye care.', 367),
  ('optometry_vision_therapy', 'eye', 'Optometry, contact lens, low-vision aids and vision therapy.', 20),
  ('general_dentistry', 'dental', 'General, family and preventive dentistry.', 13800),
  ('endodontics', 'dental', 'Endodontics / root canal therapy.', 3870),
  ('orthodontics', 'dental', 'Orthodontics and dentofacial orthopedics.', 3600),
  ('prosthodontics', 'dental', 'Prosthodontics, crowns, bridges and dentures.', 2510),
  ('periodontics', 'dental', 'Periodontics and periodontal surgery.', 980),
  ('pediatric_dentistry', 'dental', 'Pediatric dentistry / pedodontics.', 2060),
  ('cosmetic_dentistry', 'dental', 'Aesthetic / cosmetic dentistry, whitening and smile design.', 2200),
  ('oral_maxillofacial_surgery', 'dental', 'Oral and maxillofacial surgery including dentoalveolar, orthognathic and craniofacial.', 3650),
  ('dental_implantology', 'dental', 'Dental implants and implantology.', 140),
  ('oral_medicine_pathology', 'dental', 'Oral medicine, oral pathology and oral radiology.', 300),
  ('dental_anesthesia_sedation', 'dental', 'Dental anesthesia and sedation / pain-free dentistry.', 120),
  ('laser_dentistry', 'dental', 'Laser dentistry.', 44),
  ('public_health_dentistry', 'dental', 'Public health / community dentistry.', 12),
  ('medical_oncology', 'cancer', 'Medical oncology and chemotherapy / immunotherapy.', 2700),
  ('surgical_oncology', 'cancer', 'Surgical oncology / oncosurgery.', 1410),
  ('radiation_oncology', 'cancer', 'Radiation oncology / radiotherapy.', 180),
  ('gynecologic_oncology', 'cancer', 'Gynecologic oncology.', 270),
  ('neuro_oncology', 'cancer', 'Neuro-oncology (medical and surgical).', 62),
  ('orthopedic_oncology', 'cancer', 'Orthopedic / musculoskeletal oncology.', 100),
  ('pediatric_hematology_oncology', 'maternal_child', 'Pediatric hematology-oncology.', 175),
  ('radiology', 'diagnostics', 'Diagnostic radiology and imaging including breast, neuro, MSK, IR and cardiothoracic imaging.', 6400),
  ('nuclear_medicine', 'diagnostics', 'Nuclear medicine and molecular imaging.', 325),
  ('pathology', 'diagnostics', 'Anatomic and clinical pathology including histopathology, cytology, dermatopathology.', 4960),
  ('laboratory_medicine', 'diagnostics', 'Laboratory medicine: microbiology, biochemistry, serology, transfusion/blood bank, molecular diagnostics.', 350),
  ('medical_genetics', 'diagnostics', 'Medical genetics and genomics.', 35),
  ('endoscopy', 'diagnostics', 'Diagnostic / therapeutic endoscopy.', 6),
  ('preventive_medicine', 'primary_care', 'Preventive medicine, lifestyle, occupational, community and public-health programs.', 1050),
  ('nutrition_dietetics', 'primary_care', 'Nutrition and dietetics.', 110),
  ('podiatry', 'primary_care', 'Podiatry and diabetic foot / limb-salvage care.', 260),
  ('endocrine_surgery', 'surgery', 'Endocrine surgery.', 64),
  ('breast_surgery', 'surgery', 'Breast surgery.', 132),
  ('complementary_alternative_medicine', 'primary_care', 'Ayurveda, homeopathy and other complementary / integrative medicine.', 45),
  ('pharmacy', 'diagnostics', 'Pharmacy / clinical pharmacology services.', 17),
  ('other_unspecified', 'other', 'Catch-all for rare, ambiguous or non-clinical tokens that cannot be confidently mapped to a clinical canonical.', 500)
) AS t(specialty_canonical, family, description, approx_occurrences)
