-- map_specialty_raw_to_canonical
-- Universe: explode facilities.specialties (org_type='facility'); map each raw token to ONE specialty_canonical.
-- Strategy: (1) normalize raw token (British->US then strip non-alnum); (2) exact match to normalized canonical name
--           or any normalized raw_example from grounding taxonomy; (3) ordered family-stem regex fallback;
--           (4) else 'other_unspecified'. Canonical lookup (423 norm keys) materialized from grounding.json taxonomy.
CREATE OR REPLACE TABLE workspace.virtue_foundation_enriched.map_specialty_raw_to_canonical AS
WITH base AS (
  SELECT unique_id, from_json(specialties,'array<string>') arr
  FROM databricks_virtue_foundation_dataset_dais_2026.virtue_foundation_dataset.facilities
  WHERE organization_type='facility' AND specialties IS NOT NULL AND specialties NOT IN ('null','[]','')
),
ex AS (
  SELECT trim(s) AS raw_token
  FROM base LATERAL VIEW explode(arr) t AS s
  WHERE trim(s)<>'' AND lower(trim(s))<>'null'
),
tokens AS (
  SELECT raw_token, COUNT(*) AS n_occ FROM ex GROUP BY raw_token
),
canon_lookup(norm_key, specialty_canonical) AS (
  VALUES
  ('internalmedicine','internal_medicine'),
  ('generalmedicine','internal_medicine'),
  ('generalphysician','internal_medicine'),
  ('hospitalmedicine','internal_medicine'),
  ('familymedicine','family_medicine'),
  ('pediatrics','pediatrics'),
  ('pediatricsandneonatology','pediatrics'),
  ('adolescentmedicine','adolescent_medicine'),
  ('neonatology','neonatology'),
  ('neonatologyperinatalmedicine','neonatology'),
  ('neonatalperinatalmedicine','neonatology'),
  ('neonatalperinatal','neonatology'),
  ('obstetricsgynecology','obstetrics_gynecology'),
  ('gynecologyandobstetrics','obstetrics_gynecology'),
  ('obstetricsandmaternitycare','obstetrics_gynecology'),
  ('gynecology','obstetrics_gynecology'),
  ('obstetricsandgynecology','obstetrics_gynecology'),
  ('obstetrics','obstetrics_gynecology'),
  ('maternalfetalmedicine','maternal_fetal_medicine'),
  ('maternalfetalmedicineorperinatology','maternal_fetal_medicine'),
  ('reproductiveendocrinologyinfertility','reproductive_endocrinology_infertility'),
  ('reproductiveendocrinologyandinfertility','reproductive_endocrinology_infertility'),
  ('infertility','reproductive_endocrinology_infertility'),
  ('ivf','reproductive_endocrinology_infertility'),
  ('fertility','reproductive_endocrinology_infertility'),
  ('reproductivemedicine','reproductive_endocrinology_infertility'),
  ('cryopreservation','reproductive_endocrinology_infertility'),
  ('familyplanningcontraception','family_planning_contraception'),
  ('familyplanningandcomplexcontraception','family_planning_contraception'),
  ('urogynecology','urogynecology'),
  ('urogynecologyandreconstructivepelvissurgery','urogynecology'),
  ('femalepelvicmedicineandreconstructivesurgery','urogynecology'),
  ('maternalchildhealth','maternal_child_health'),
  ('maternalandchildhealth','maternal_child_health'),
  ('cardiology','cardiology'),
  ('interventionalcardiology','cardiology'),
  ('noninvasivecardiology','cardiology'),
  ('preventivecardiology','cardiology'),
  ('cardiologist','cardiology'),
  ('pediatriccardiology','pediatric_cardiology'),
  ('gastroenterology','gastroenterology'),
  ('medicalgastroenterology','gastroenterology'),
  ('gastroenterologyandhepatology','gastroenterology'),
  ('hepatology','gastroenterology'),
  ('nephrology','nephrology'),
  ('dialysis','nephrology'),
  ('nephrologyanddialysis','nephrology'),
  ('nephrologyincludingdialysis','nephrology'),
  ('renalsciences','nephrology'),
  ('pulmonology','pulmonology'),
  ('pulmonarymedicine','pulmonology'),
  ('respiratorymedicine','pulmonology'),
  ('chestmedicine','pulmonology'),
  ('endocrinologydiabetes','endocrinology_diabetes'),
  ('endocrinologyanddiabetesandmetabolism','endocrinology_diabetes'),
  ('endocrinology','endocrinology_diabetes'),
  ('diabetology','endocrinology_diabetes'),
  ('diabetesandendocrinology','endocrinology_diabetes'),
  ('diabetologist','endocrinology_diabetes'),
  ('rheumatology','rheumatology'),
  ('rheumatologyandclinicalimmunology','rheumatology'),
  ('clinicalimmunologyandrheumatology','rheumatology'),
  ('infectiousdiseases','infectious_diseases'),
  ('infectiousdiseasecontrol','infectious_diseases'),
  ('allergyimmunology','allergy_immunology'),
  ('allergyandimmunology','allergy_immunology'),
  ('clinicalimmunology','allergy_immunology'),
  ('immunology','allergy_immunology'),
  ('rheumatologyandimmunology','allergy_immunology'),
  ('hematology','hematology'),
  ('hematooncology','hematology'),
  ('bonemarrowtransplant','hematology'),
  ('geriatricmedicine','geriatric_medicine'),
  ('geriatricsinternalmedicine','geriatric_medicine'),
  ('geriatricinternalmedicine','geriatric_medicine'),
  ('sleepmedicine','sleep_medicine'),
  ('sleepmedicineotolaryngology','sleep_medicine'),
  ('sleepmedicineneurology','sleep_medicine'),
  ('pediatricsleepmedicine','sleep_medicine'),
  ('sportsmedicine','sports_medicine'),
  ('sportsmedicinepmr','sports_medicine'),
  ('sportsinternalmedicine','sports_medicine'),
  ('orthopedicsportsmedicine','sports_medicine'),
  ('addictionmedicine','addiction_medicine'),
  ('addictionmedicinepm','addiction_medicine'),
  ('addictioninternalmedicine','addiction_medicine'),
  ('substanceusedisorder','addiction_medicine'),
  ('addictionmedicinepmr','addiction_medicine'),
  ('andrologysexualmedicine','andrology_sexual_medicine'),
  ('andrologyandmalefertility','andrology_sexual_medicine'),
  ('andrology','andrology_sexual_medicine'),
  ('sexology','andrology_sexual_medicine'),
  ('sexualmedicine','andrology_sexual_medicine'),
  ('andrologyandsexology','andrology_sexual_medicine'),
  ('palliativemedicine','palliative_medicine'),
  ('hospiceandpalliativeinternalmedicine','palliative_medicine'),
  ('palliativecare','palliative_medicine'),
  ('hospiceandpalliativemedicine','palliative_medicine'),
  ('painpalliativemedicine','palliative_medicine'),
  ('criticalcaremedicine','critical_care_medicine'),
  ('criticalcare','critical_care_medicine'),
  ('icuandcriticalcare','critical_care_medicine'),
  ('intensivecareunit','critical_care_medicine'),
  ('internalmedicineandcriticalcare','critical_care_medicine'),
  ('pediatriccriticalcare','pediatric_critical_care'),
  ('pediatriccriticalcaremedicine','pediatric_critical_care'),
  ('emergencymedicine','emergency_medicine'),
  ('accidentandemergency','emergency_medicine'),
  ('pediatricemergencymedicine','pediatric_emergency_medicine'),
  ('anesthesiology','anesthesiology'),
  ('anesthesia','anesthesiology'),
  ('cardiacanesthesia','anesthesiology'),
  ('obstetricanesthesiology','anesthesiology'),
  ('painmedicineanesthesiology','anesthesiology'),
  ('painmedicine','pain_medicine'),
  ('painmedicinepmr','pain_medicine'),
  ('painmanagement','pain_medicine'),
  ('painpalliative','pain_medicine'),
  ('physicalmedicinerehab','physical_medicine_rehab'),
  ('physicalmedicineandrehabilitation','physical_medicine_rehab'),
  ('rehabilitation','physical_medicine_rehab'),
  ('neurorehabilitation','physical_medicine_rehab'),
  ('cancerrehabilitation','physical_medicine_rehab'),
  ('geriatricrehabilitation','physical_medicine_rehab'),
  ('physiotherapy','physiotherapy'),
  ('occupationaltherapy','occupational_therapy'),
  ('occupationalandvocationalrehabilitation','occupational_therapy'),
  ('speechaudiology','speech_audiology'),
  ('speechtherapy','speech_audiology'),
  ('audiology','speech_audiology'),
  ('audiologyandspeechtherapy','speech_audiology'),
  ('prostheticsorthoticsrehab','prosthetics_orthotics_rehab'),
  ('amputeeandprostheticsandorthoticsrehabilitation','prosthetics_orthotics_rehab'),
  ('spinalcordinjurymedicine','prosthetics_orthotics_rehab'),
  ('dermatology','dermatology'),
  ('cosmeticdermatology','dermatology'),
  ('proceduraldermatology','dermatology'),
  ('dermatosurgery','dermatology'),
  ('hairandnaildisorders','dermatology'),
  ('pediatricdermatology','pediatric_dermatology'),
  ('psychiatry','psychiatry'),
  ('addictionpsychiatry','psychiatry'),
  ('geriatricpsychiatry','psychiatry'),
  ('forensicpsychiatry','psychiatry'),
  ('consultationliaisonpsychiatry','psychiatry'),
  ('emergencypsychiatry','psychiatry'),
  ('childadolescentpsychiatry','child_adolescent_psychiatry'),
  ('childandadolescentpsychiatry','child_adolescent_psychiatry'),
  ('psychology','psychology'),
  ('clinicalpsychology','psychology'),
  ('neurology','neurology'),
  ('neuromedicine','neurology'),
  ('epilepsyneurology','neurology'),
  ('movementdisorders','neurology'),
  ('vascularneurology','neurology'),
  ('clinicalneurophysiology','neurology'),
  ('headachemedicine','neurology'),
  ('pediatricneurology','pediatric_neurology'),
  ('childneurology','pediatric_neurology'),
  ('pediatricneurodevelopmentaldisabilities','pediatric_neurology'),
  ('neurosurgery','neurosurgery'),
  ('spineneurosurgery','neurosurgery'),
  ('skullbaseneurosurgery','neurosurgery'),
  ('cerebrovascularneurosurgery','neurosurgery'),
  ('functionalneurosurgery','neurosurgery'),
  ('pediatricneurosurgery','pediatric_neurosurgery'),
  ('generalsurgery','general_surgery'),
  ('laparoscopicsurgery','general_surgery'),
  ('roboticsurgery','general_surgery'),
  ('herniasurgery','general_surgery'),
  ('generalandlaparoscopicsurgery','general_surgery'),
  ('orthopedicsurgery','orthopedic_surgery'),
  ('orthopedics','orthopedic_surgery'),
  ('jointreconstructionsurgery','orthopedic_surgery'),
  ('jointreplacementsurgery','orthopedic_surgery'),
  ('footandankleorthopedicsurgery','orthopedic_surgery'),
  ('shoulderandelboworthopedicsurgery','orthopedic_surgery'),
  ('arthroscopicsurgery','orthopedic_surgery'),
  ('pediatricorthopedicsurgery','pediatric_orthopedic_surgery'),
  ('pediatricorthopedics','pediatric_orthopedic_surgery'),
  ('handsurgery','hand_surgery'),
  ('handorupperextremityandperipheralnervesurgery','hand_surgery'),
  ('handandupperextremitiessurgery','hand_surgery'),
  ('spinesurgery','spine_surgery'),
  ('orthopedicspinesurgery','spine_surgery'),
  ('cardiothoracicsurgery','cardiothoracic_surgery'),
  ('cardiacsurgery','cardiothoracic_surgery'),
  ('generalthoracicsurgery','cardiothoracic_surgery'),
  ('thoracicsurgery','cardiothoracic_surgery'),
  ('cardiovascularsurgery','cardiothoracic_surgery'),
  ('vascularsurgery','vascular_surgery'),
  ('endovascularsurgery','vascular_surgery'),
  ('vascularendovascularsurgery','vascular_surgery'),
  ('plasticreconstructivesurgery','plastic_reconstructive_surgery'),
  ('plasticsurgery','plastic_reconstructive_surgery'),
  ('reconstructiveplasticsurgery','plastic_reconstructive_surgery'),
  ('aestheticandcosmeticsurgery','plastic_reconstructive_surgery'),
  ('cosmeticsurgery','plastic_reconstructive_surgery'),
  ('burnandtraumaplasticsurgery','plastic_reconstructive_surgery'),
  ('plasticandreconstructivesurgery','plastic_reconstructive_surgery'),
  ('colorectalsurgery','colorectal_surgery'),
  ('proctology','colorectal_surgery'),
  ('gihpbsurgery','gi_hpb_surgery'),
  ('hepatopancreatobiliarysurgery','gi_hpb_surgery'),
  ('surgicalgastroenterology','gi_hpb_surgery'),
  ('gastrointestinalsurgery','gi_hpb_surgery'),
  ('uppergiandforegutsurgery','gi_hpb_surgery'),
  ('hepatobiliarysurgery','gi_hpb_surgery'),
  ('gastrosurgery','gi_hpb_surgery'),
  ('bariatricmetabolicsurgery','bariatric_metabolic_surgery'),
  ('bariatricsurgery','bariatric_metabolic_surgery'),
  ('metabolicsurgery','bariatric_metabolic_surgery'),
  ('bariatrics','bariatric_metabolic_surgery'),
  ('obesity','bariatric_metabolic_surgery'),
  ('transplantsurgery','transplant_surgery'),
  ('livertransplantation','transplant_surgery'),
  ('kidneytransplantation','transplant_surgery'),
  ('organtransplant','transplant_surgery'),
  ('organtransplantation','transplant_surgery'),
  ('pediatricsurgery','pediatric_surgery'),
  ('pediatricssurgery','pediatric_surgery'),
  ('pediatriccardiacsurgery','pediatric_surgery'),
  ('urology','urology'),
  ('minimallyinvasivesurgeryandendourology','urology'),
  ('urologiconcology','urology'),
  ('renaltransplantationurology','urology'),
  ('femaleurology','urology'),
  ('urosurgery','urology'),
  ('reconstructiveurology','urology'),
  ('neurourology','urology'),
  ('pediatricurology','pediatric_urology'),
  ('otolaryngology','otolaryngology'),
  ('ent','otolaryngology'),
  ('otorhinolaryngology','otolaryngology'),
  ('rhinology','otolaryngology'),
  ('laryngology','otolaryngology'),
  ('headandnecksurgeryotolaryngology','otolaryngology'),
  ('neurotologyandotology','otolaryngology'),
  ('pediatricotolaryngology','pediatric_otolaryngology'),
  ('ophthalmology','ophthalmology'),
  ('eyecheckup','ophthalmology'),
  ('lowvision','ophthalmology'),
  ('dryeye','ophthalmology'),
  ('squinteyetreatment','ophthalmology'),
  ('binocularvisionandorthoptics','ophthalmology'),
  ('cataractanteriorsegment','cataract_anterior_segment'),
  ('cataractandanteriorsegmentsurgery','cataract_anterior_segment'),
  ('retinavitreoretinal','retina_vitreoretinal'),
  ('retinaandvitreoretinalophthalmology','retina_vitreoretinal'),
  ('diabeticretinopathy','retina_vitreoretinal'),
  ('retinadiseases','retina_vitreoretinal'),
  ('retinaldetachment','retina_vitreoretinal'),
  ('retinopathyofprematurity','retina_vitreoretinal'),
  ('refractivesurgery','refractive_surgery'),
  ('refractivesurgeryophthalmology','refractive_surgery'),
  ('lasiksurgery','refractive_surgery'),
  ('contouralasik','refractive_surgery'),
  ('prksurgery','refractive_surgery'),
  ('iclsurgery','refractive_surgery'),
  ('keratoconus','refractive_surgery'),
  ('glaucoma','glaucoma'),
  ('glaucomaophthalmology','glaucoma'),
  ('cornea','cornea'),
  ('corneaophthalmology','cornea'),
  ('oculoplastyorbit','oculoplasty_orbit'),
  ('oculoplasticsandreconstructiveorbitalsurgery','oculoplasty_orbit'),
  ('oculoplasty','oculoplasty_orbit'),
  ('orbitandoculoplasty','oculoplasty_orbit'),
  ('ocularprosthesis','oculoplasty_orbit'),
  ('pediatricstrabismusophthalmology','pediatric_strabismus_ophthalmology'),
  ('pediatricsandstrabismusophthalmology','pediatric_strabismus_ophthalmology'),
  ('pediatricophthalmology','pediatric_strabismus_ophthalmology'),
  ('squintsurgery','pediatric_strabismus_ophthalmology'),
  ('squint','pediatric_strabismus_ophthalmology'),
  ('squintorthoptics','pediatric_strabismus_ophthalmology'),
  ('neuroophthalmology','neuro_ophthalmology'),
  ('uveitis','uveitis'),
  ('uveitisophthalmology','uveitis'),
  ('uveaophthalmology','uveitis'),
  ('uveaocularinflammation','uveitis'),
  ('ocularoncology','ocular_oncology'),
  ('eyetraumaemergency','eye_trauma_emergency'),
  ('eyetraumaandemergencyeyecare','eye_trauma_emergency'),
  ('optometryvisiontherapy','optometry_vision_therapy'),
  ('contactlensandlowvisionaids','optometry_vision_therapy'),
  ('visiontherapy','optometry_vision_therapy'),
  ('visionenhancementandrehabilitation','optometry_vision_therapy'),
  ('generaldentistry','general_dentistry'),
  ('dentistry','general_dentistry'),
  ('familydentistry','general_dentistry'),
  ('preventivedentistry','general_dentistry'),
  ('conservativedentistry','general_dentistry'),
  ('restorativedentistry','general_dentistry'),
  ('dental','general_dentistry'),
  ('endodontics','endodontics'),
  ('endodontist','endodontics'),
  ('orthodontics','orthodontics'),
  ('dentofacialorthopedics','orthodontics'),
  ('jaworthopedics','orthodontics'),
  ('prosthodontics','prosthodontics'),
  ('prostheticdentistry','prosthodontics'),
  ('crownsandbridges','prosthodontics'),
  ('dentures','prosthodontics'),
  ('maxillofacialprosthesis','prosthodontics'),
  ('prosthodontist','prosthodontics'),
  ('periodontics','periodontics'),
  ('periodontology','periodontics'),
  ('periodontalsurgery','periodontics'),
  ('periodontalplasticsurgery','periodontics'),
  ('pediatricdentistry','pediatric_dentistry'),
  ('pedodontics','pediatric_dentistry'),
  ('pedodonticsandpreventivedentistry','pediatric_dentistry'),
  ('cosmeticdentistry','cosmetic_dentistry'),
  ('aestheticdentistry','cosmetic_dentistry'),
  ('teethwhitening','cosmetic_dentistry'),
  ('smiledesigning','cosmetic_dentistry'),
  ('oralmaxillofacialsurgery','oral_maxillofacial_surgery'),
  ('oralandmaxillofacialsurgery','oral_maxillofacial_surgery'),
  ('dentoalveolarsurgery','oral_maxillofacial_surgery'),
  ('orthognathicsurgery','oral_maxillofacial_surgery'),
  ('craniofacialandcleftoralmaxillofacialsurgery','oral_maxillofacial_surgery'),
  ('cosmeticmaxillofacialsurgery','oral_maxillofacial_surgery'),
  ('oralsurgery','oral_maxillofacial_surgery'),
  ('dentalimplantology','dental_implantology'),
  ('dentalimplants','dental_implantology'),
  ('dentalimplant','dental_implantology'),
  ('implantology','dental_implantology'),
  ('implantdentistry','dental_implantology'),
  ('implants','dental_implantology'),
  ('implantologist','dental_implantology'),
  ('oralmedicinepathology','oral_medicine_pathology'),
  ('oralmedicine','oral_medicine_pathology'),
  ('oralpathology','oral_medicine_pathology'),
  ('oralmedicineandradiology','oral_medicine_pathology'),
  ('oralandmaxillofacialpathology','oral_medicine_pathology'),
  ('dentalanesthesiasedation','dental_anesthesia_sedation'),
  ('dentalanesthesia','dental_anesthesia_sedation'),
  ('sedationdentistry','dental_anesthesia_sedation'),
  ('painfreedentistry','dental_anesthesia_sedation'),
  ('laserdentistry','laser_dentistry'),
  ('publichealthdentistry','public_health_dentistry'),
  ('communitydentistry','public_health_dentistry'),
  ('medicaloncology','medical_oncology'),
  ('oncology','medical_oncology'),
  ('clinicaloncology','medical_oncology'),
  ('immunotherapy','medical_oncology'),
  ('cancercare','medical_oncology'),
  ('thoraciconcology','medical_oncology'),
  ('gastrointestinaloncology','medical_oncology'),
  ('surgicaloncology','surgical_oncology'),
  ('oncosurgery','surgical_oncology'),
  ('headandneckoncology','surgical_oncology'),
  ('radiationoncology','radiation_oncology'),
  ('radiotherapy','radiation_oncology'),
  ('preventiveoncology','radiation_oncology'),
  ('gynecologiconcology','gynecologic_oncology'),
  ('gynecologicaloncology','gynecologic_oncology'),
  ('neurooncology','neuro_oncology'),
  ('neurooncologyneurosurgery','neuro_oncology'),
  ('orthopediconcology','orthopedic_oncology'),
  ('pediatrichematologyoncology','pediatric_hematology_oncology'),
  ('pediatriconcology','pediatric_hematology_oncology'),
  ('pediatrichematooncology','pediatric_hematology_oncology'),
  ('radiology','radiology'),
  ('diagnosticradiology','radiology'),
  ('interventionalradiology','radiology'),
  ('breastimaging','radiology'),
  ('neuroradiology','radiology'),
  ('mammography','radiology'),
  ('radiodiagnosis','radiology'),
  ('musculoskeletalradiology','radiology'),
  ('nuclearmedicine','nuclear_medicine'),
  ('nuclearmedicineandmolecularimaging','nuclear_medicine'),
  ('pathology','pathology'),
  ('clinicalpathology','pathology'),
  ('anatomicpathology','pathology'),
  ('histopathology','pathology'),
  ('cytology','pathology'),
  ('dermatopathology','pathology'),
  ('cytopathology','pathology'),
  ('laboratorymedicine','laboratory_medicine'),
  ('microbiology','laboratory_medicine'),
  ('biochemistry','laboratory_medicine'),
  ('serology','laboratory_medicine'),
  ('transfusionmedicine','laboratory_medicine'),
  ('bloodbank','laboratory_medicine'),
  ('moleculardiagnostics','laboratory_medicine'),
  ('clinicalbiochemistry','laboratory_medicine'),
  ('medicalgenetics','medical_genetics'),
  ('genetics','medical_genetics'),
  ('genomics','medical_genetics'),
  ('neurogeneticsandrarediseases','medical_genetics'),
  ('endoscopy','endoscopy'),
  ('preventivemedicine','preventive_medicine'),
  ('chronicdiseasepreventionandlifestylemedicine','preventive_medicine'),
  ('publichealth','preventive_medicine'),
  ('communitymedicine','preventive_medicine'),
  ('occupationalandenvironmentalmedicine','preventive_medicine'),
  ('healthcheckup','preventive_medicine'),
  ('nutritiondietetics','nutrition_dietetics'),
  ('nutritionanddietetics','nutrition_dietetics'),
  ('dietetics','nutrition_dietetics'),
  ('nutrition','nutrition_dietetics'),
  ('dietitian','nutrition_dietetics'),
  ('dieteticsandnutrition','nutrition_dietetics'),
  ('dietitiannutritionist','nutrition_dietetics'),
  ('podiatry','podiatry'),
  ('podiatricdiabeticlimbsalvageandwoundcare','podiatry'),
  ('footsurgery','podiatry'),
  ('endocrinesurgery','endocrine_surgery'),
  ('breastsurgery','breast_surgery'),
  ('complementaryalternativemedicine','complementary_alternative_medicine'),
  ('ayurveda','complementary_alternative_medicine'),
  ('homeopathy','complementary_alternative_medicine'),
  ('alternativemedicine','complementary_alternative_medicine'),
  ('integrativemedicine','complementary_alternative_medicine'),
  ('pharmacy','pharmacy'),
  ('pharmacology','pharmacy'),
  ('otherunspecified','other_unspecified'),
  ('multispeciality','other_unspecified'),
  ('cardiacsciences','other_unspecified'),
  ('specialeducation','other_unspecified'),
  ('clinicalinformatics','other_unspecified')
),
normed AS (
  SELECT raw_token, n_occ, regexp_replace(replace(replace(replace(replace(replace(replace(lower(raw_token),'paediatric','pediatric'),'haemat','hemat'),'anaesth','anesth'),'gynaec','gynec'),'orthopaed','orthoped'),'paed','ped'),'[^a-z0-9]','') AS nk FROM tokens
),
exact AS (
  SELECT n.raw_token, n.n_occ, n.nk, cl.specialty_canonical
  FROM normed n
  LEFT JOIN canon_lookup cl ON n.nk = cl.norm_key
),
mapped AS (
  SELECT raw_token, n_occ,
    CASE
      WHEN specialty_canonical IS NOT NULL THEN specialty_canonical
      -- ordered family-stem regex fallback on normalized token (nk)
      WHEN nk RLIKE 'oncolog'                          THEN 'medical_oncology'
      WHEN nk RLIKE 'ophthalmolog|ophthalmic|eyecare|^eye' THEN 'ophthalmology'
      WHEN nk RLIKE 'dental|dentist|dentofacial|odont' THEN 'general_dentistry'
      WHEN nk RLIKE 'patholog|laborator|microbiolog|biochemistr' THEN 'pathology'
      WHEN nk RLIKE 'rehab|physiother|physiatr|^pmr|pmrand' THEN 'physical_medicine_rehab'
      -- additional grounded family-stem fallbacks (align with grounding canonicalization_rules)
      WHEN nk RLIKE 'psychiatr'                        THEN 'psychiatry'
      WHEN nk RLIKE 'otolaryngolog|otorhinolaryngolog' THEN 'otolaryngology'
      WHEN nk RLIKE 'dermatolog'                       THEN 'dermatology'
      WHEN nk RLIKE 'urolog'                           THEN 'urology'
      WHEN nk RLIKE 'radiolog'                         THEN 'radiology'
      WHEN nk RLIKE 'anesth'                           THEN 'anesthesiology'
      WHEN nk RLIKE 'gynec|menopause'                  THEN 'obstetrics_gynecology'
      WHEN nk RLIKE 'neurosurg'                        THEN 'neurosurgery'
      WHEN nk RLIKE 'neurolog|neuromuscular|neurocritical|braininjury|cognitiveandbehavioral|neuroimmunolog' THEN 'neurology'
      WHEN nk RLIKE 'cardiolog'                        THEN 'cardiology'
      WHEN nk RLIKE 'pediatric'                        THEN 'pediatrics'
      WHEN nk RLIKE 'surger|surgical|surgery'          THEN 'general_surgery'
      ELSE 'other_unspecified'
    END AS specialty_canonical
  FROM exact
)
SELECT raw_token, specialty_canonical, n_occ
FROM mapped;
